<?php
defined('HTTP_STATUS_OK') || define('HTTP_STATUS_OK', 200);
defined('HTTP_STATUS_CREATED') || define('HTTP_STATUS_CREATED', 201);
defined('HTTP_STATUS_ACCEPTED') || define('HTTP_STATUS_ACCEPTED', 202);

defined('HTTP_STATUS_BAD_REQUEST') || define('HTTP_STATUS_BAD_REQUEST', 400);
defined('HTTP_STATUS_UNAUTHORIZED') || define('HTTP_STATUS_UNAUTHORIZED', 401);
defined('HTTP_STATUS_FORBIDDEN') || define('HTTP_STATUS_FORBIDDEN', 403);
defined('HTTP_STATUS_NOT_FOUND') || define('HTTP_STATUS_NOT_FOUND', 404);

defined('HTTP_STATUS_INTERNAL_ERROR') || define('HTTP_STATUS_INTERNAL_ERROR', 500);
defined('HTTP_STATUS_BAD_GATEWAY') || define('HTTP_STATUS_BAD_GATEWAY', 502);
defined('HTTP_STATUS_SERVICE_UNAVAILABLE') || define('HTTP_STATUS_SERVICE_UNAVAILABLE', 503);
